config/routes.rb
FoodSupply::Application.routes.draw do
  resources :inventory_items

end

app/models/inventory_item.rb
class InventoryItem < ActiveRecord::Base
  validates_presence_of :title, :description, :quantity
  validates_numericality_of :quantity, only_integer: true, greater_than_or_equal_to: 0
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/inventory_items_controller.rb
class InventoryItemsController < ApplicationController
  def index
    @inventory_items = InventoryItem.all
  end

  def new
    @inventory_item = InventoryItem.new
  end

  def show
    @inventory_item = InventoryItem.find(params[:id])
  end

  def edit
    @inventory_item = InventoryItem.find(params[:id])
  end

  def create
    @inventory_item = InventoryItem.new(inventory_item_params)
    if @inventory_item.save
      redirect_to @inventory_item,
        notice: 'Inventory item was successfully created'
    else
      render :new
    end
  end

  def update
    @inventory_item = InventoryItem.new(inventory_item_params)

    if @inventory_item.update(inventory_item_params)
      redirect_to inventory_item_path(@inventory_item), notice: 'Inventory item was successfully updated!'
    else
      render action: 'edit'
    end
  end

  def destroy
    InventoryItem.find(params[:id]).destroy
    redirect_to inventory_item_path, notice: 'Inventory item was succesfully destroyed'
  end

  private

  def inventory_item_params
    params.require(:inventory_item).permit(:title, :description, :quantity)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inventory_items_helper.rb
module InventoryItemsHelper
end

app/views/inventory_items/_form.html.erb
<%= form_for(@inventory_item) do |f| %>
  <% if @inventory_item.errors.any? %>
    <div>
      <h2><%= pluralize(@inventory_item.errors.count, "error") %> prohibited this issue from being saved:</h2>
      <ul>
        <% @inventory_item.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>

  <div>
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inventory_items/index.html.erb
<h1>Inventory Items Index</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Quantity</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @inventory_items.each do |food_item| %>
      <tr>
        <td><%= food_item.title %></td>
        <td><%= food_item.description %></td>
        <td><%= food_item.quantity %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Inventory Item', new_inventory_item_path %>

app/views/inventory_items/new.html.erb
<h1>Create Inventory Item</h1>

<%= render 'form', inventory_item: @inventory_item %>

app/views/inventory_items/show.html.erb
<h1><%= @inventory_item.title %></h1>

<p>
  <strong>Description:</strong>
  <%= @inventory_item.description %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @inventory_item.quantity %>
</p>

<%= link_to 'Back', inventory_items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FoodSupply</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>